# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55e03e3c0af5440d1a4ff00bff796d9e94d089bf252b91f35929ea3678082709b6ce4c6c7c6c34489624e86a8b80b8dca93535064dbab143de7d1354bba7c723

test:
  secret_key_base: 5c5e7cb5ed4d44dd12bf902edbaba8e0847ef56805001d51aa467d9be56a8c080c7be00fa983efc64fbd18ea7f13a26695b837abe75c9ce9819a63693c36132a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
